pdf:
	pandoc --from=markdown \
		--to=pdf \
		-o docs/README.pdf \
		-V colorlinks=true \
		docs/Overview.md docs/Tasks.md docs/Challenge.md

	pandoc --from=markdown \
		--to=pdf \
		-o docs/MiniScheme.pdf \
		-V colorlinks=true \
		docs/MiniScheme.md
